### ISSUE TITLE
Is this ready for use?

### ISSUE THREAD

**Issue by zqpvr** [CachyOS/CachyOS-Handheld#1]

**Comment by ptr1337** [comment]
No, not yet.

There are still here and there issues, which needs to be resolved but it improves.
It is aimed to provide a option for the installer with the May release, but it depends how we get everything managed.

**Comment by ptr1337** [comment]
> Could I install it manually, by moving the usr and etc folders to root? Or is there a different way?

The package is already in our repo and can be installed there, but there are still some bugs

**Comment by ptr1337** [comment]
> Alright, I can test it. I have a steam deck running bazzite right now and am thinking to switch to CachyOS.

Sure, you can test it but there are still here and there bugs. Sadly we developers dont have currently a steam deck, but were working closely with the community.



> What's the package name?

`sudo pacman -S cachyos-deckify` after the installation

Really expect bugs, it isnt perfect yet and not everything is done. But contribution, reports and fixes are welcome.

**Comment by ptr1337** [comment]
> Also, does steam startup automatically after exiting gamemode?

It should, but we got some reports that it doesnt work yet.
Also for the steamdeck we miss still the steam-firmware right now.

**Comment by ptr1337** [comment]
So, we made a bunch of progress and an initial testing ISO is provided to our testers.
Plan is to make the first Release of it in Mid of May.

**Comment by ptr1337** [comment]
Its ready, closing
