### ISSUE TITLE
Ventoy

### ISSUE THREAD

**Issue by massatt212** [CachyOS/CachyOS-Handheld#11]
Just updated ventoy and now it's a different error ![PXL_20240524_141649759.jpg](https://github.com/CachyOS/CachyOS-Handheld/assets/43518479/980bfe61-d88e-4f9a-9c30-0525b61566bd)

It's a fresh download also

**Comment by ptr1337** [comment]
Probably corrupt means, that you either have a corruption when downloading or equal.

**Comment by massatt212** [comment]
I use Rufus on a other flash drive and it loads up, I have similar problems on some motherboard, sometimes with chimeraOS bazzite use to do the same thing now the ventoy version works.

**Comment by massatt212** [comment]
Which file format should I use? Cause I'm using exfat and fat32 can't read large files and I don't know if NTFS will be good for Linux iso

**Comment by ptr1337** [comment]
> Which file format should I use? Cause I'm using exfat and fat32 can't read large files and I don't know if NTFS will be good for Linux iso

You can not install with NTFS. Just use the default one - BTRFS.

**Comment by massatt212** [comment]
> > Which file format should I use? Cause I'm using exfat and fat32 can't read large files and I don't know if NTFS will be good for Linux iso
> 
> You can not install with NTFS. Just use the default one - BTRFS.

im talking about the ventoy partition not the install partition for cachyos
i dont want to open another issue im also having bluetooth problems

Bus 001 Device 003: ID 0489:e0cd Foxconn / Hon Hai MediaTek Bluetooth Adapter

**Comment by ptr1337** [comment]
> > > Which file format should I use? Cause I'm using exfat and fat32 can't read large files and I don't know if NTFS will be good for Linux iso
> > 
> > 
> > You can not install with NTFS. Just use the default one - BTRFS.
> 
> im talking about the ventoy partition not the install partition for cachyos i dont want to open another issue im also having bluetooth problems
> 
> Bus 001 Device 003: ID 0489:e0cd Foxconn / Hon Hai MediaTek Bluetooth Adapter

Actually, just flash it with Etcher/Rufus. That should work fine.
The latest rufus version, uses also now grub as bootloader.


> i dont want to open another issue im also having bluetooth problems
> Bus 001 Device 003: ID 0489:e0cd Foxconn / Hon Hai MediaTek Bluetooth Adapter

Thats a bug from the 6.9 Kernel. There will be a 6.8 Kernel installed with after the installation, wihch you can select when booting.
Here is the related upstream bugreport:
https://bugzilla.kernel.org/show_bug.cgi?id=218757

**Comment by massatt212** [comment]
ok thx you

> > > > Which file format should I use? Cause I'm using exfat and fat32 can't read large files and I don't know if NTFS will be good for Linux iso
> > > 
> > > 
> > > You can not install with NTFS. Just use the default one - BTRFS.
> > 
> > 
> > im talking about the ventoy partition not the install partition for cachyos i dont want to open another issue im also having bluetooth problems
> > Bus 001 Device 003: ID 0489:e0cd Foxconn / Hon Hai MediaTek Bluetooth Adapter
> 
> Actually, just flash it with Etcher/Rufus. That should work fine. The latest rufus version, uses also now grub as bootloader.
> 
> > i dont want to open another issue im also having bluetooth problems
> > Bus 001 Device 003: ID 0489:e0cd Foxconn / Hon Hai MediaTek Bluetooth Adapter
> 
> Thats a bug from the 6.9 Kernel. There will be a 6.8 Kernel installed with after the installation, wihch you can select when booting. Here is the related upstream bugreport: https://bugzilla.kernel.org/show_bug.cgi?id=218757

alright, with the bluetooth
but i wanted to keep all iso on one flash drive, but thats np.

**Comment by ptr1337** [comment]
Closing here, bluetooth issue got fixed

**Comment by massatt212** [comment]
When I was playing street fighter, the cachyos kernel was drooping my fps, switching linux-zen fixed the problem, I couldn't enable game mode either to set frequency to max CPU.

**Comment by ptr1337** [comment]
> When I was playing street fighter, the cachyos kernel was drooping my fps, switching linux-zen fixed the problem, I couldn't enable game mode either to set frequency to max CPU.

You should open another issue for this.
This is likely cause by Valves Scheduler (LAVD), which we use as default.

You can disable it with: 
sudo systemctl stop scx.service

to make it presisent:

sudo systemctl disable scx
This is also mentioned in the wiki and forum post. We will do final benchmarking till the release and then consider, which we put as default.
