### ISSUE TITLE
Protontricks doesnt work and ISSUES with winetricks

### ISSUE THREAD

**Issue by Bladen123** [CachyOS/CachyOS-Handheld#12]
Hello there im not sure if this is the right place to write about this problem i have.

I tryed to install protontricks , becasue winetricks thats allready preinstalled but full of errors . 

How ca i fix this problem becasue without protontricks i cant install VCruntimes for the Games.

**Comment by Pogogo007** [comment]
Could you be more specific about the issue with protontricks? Does it give an error?

**Comment by Bladen123** [comment]
if i try to use winetricks thats preinstalled , it tells me that the winetricks something with v9 isnt up to date lol and i should go with v8 or something like that 
than some strange errors follow . anyway i tryed to install protontricks is more handy and better script to install vc++ for the non steam games . but sadly i get no icon form protontricks , nothing that i can use at all . i used ArchLinux install method from protontricks . also with pipx tryed and still nothing . normaly on bazziteos it comes a icon named protontricks and just click on it works flawless. ChimeraOS even better its inside the store to flatpak install it.

**Comment by Pogogo007** [comment]
You installed protontricks using paru -S protontricks
?

**Comment by Bladen123** [comment]
No sir . i installed it with PIPX  and PIP also

PIPX:

sudo pacman -S python-pip python-pipx python-setuptools python-virtualenv

pipx install protontricks

protontricks-desktop-install

pipx upgrade protontricks

________________________________________________________________________________________________

PIP : 

sudo pacman -S python-pip python-setuptools

sudo python3 -m pip install protontricks

sudo python3 -m pip install --upgrade protontricks

python3 -m pip install --user protontricks

**Comment by ptr1337** [comment]
> No sir . i installed it with PIPX and PIP also
> 
> PIPX:
> 
> sudo pacman -S python-pip python-pipx python-setuptools python-virtualenv
> 
> pipx install protontricks
> 
> protontricks-desktop-install
> 
> pipx upgrade protontricks
> 
> PIP :
> 
> sudo pacman -S python-pip python-setuptools
> 
> sudo python3 -m pip install protontricks
> 
> sudo python3 -m pip install --upgrade protontricks
> 
> python3 -m pip install --user protontricks
> 
> EDIT:
> 
> I will try with paru -S protontricks now then

That is the wrong way installing this. You should **always** use the package manager to install package. Don't use pip, pipx or equal, as long the package is available in the official cachyos or archlinux repository.

The AUR can be also used, but these packages should be reviewed

**Comment by Bladen123** [comment]
And what is the command to install it ? with the built in package ? please

and how can i fix the winetricks telling me that the version 9 is outofdate or so ?

**Comment by ptr1337** [comment]
`paru -S protontricks` also see our wiki, how to install packages:
https://wiki.cachyos.org

**Comment by Bladen123** [comment]
This cachyOS handheld Version is best SteamOS Alternative ever , snappy , fast , i just want to say that chimeraOS, BazziteOS, Nobara SteamDeck Edition , they are not even half that good like this OS. this CachyOS is the reason i really want to try and stick to Linux.

Thank you very much Sir for this Awesome Operating System and for the help u provide me with protontricks. Wish u all good Sir

**Comment by Bladen123** [comment]
i think this OS will be second most used after windows 11 on Rog Allys and Legion Gos. Sound very good what u guys work on here. when u release the next version i will definetly donate for u guys something for your hard work. Thank you endless have a nice day mates
