### ISSUE TITLE
Switching to KDE sometimes gets stuck

### ISSUE THREAD

**Issue by Pogogo007** [CachyOS/CachyOS-Handheld#14]
Sometimes switching to desktop session (kde) will get stuck on a blackscreen with a cursor. 
Touching the screen or clicking a button causes the switch to complete normally

**Comment by ripplingsnake** [comment]
If your Steam Deck shows a blank screen when going to Desktop Mode then this is the easy fix for you.
You will need a USB keyboard or Bluetooth keyboard for this.
1. When in Game Mode press CTL-ALT-F5 to open a terminal session.
2. Enter the username - deck
Enter your sudo password when prompted.
a. rm -rf ~/.local/share/kscreen (be careful with this command make sure no typos

b. nano .bash_profile
Use the down arrow key to go to the end of the line and add this - rm -rf ~/.local/share/kscreen
3. Press CTL-X to quit nano. Press Y to save the file, and press enter to save it.
4. Type exit to logout the shell.

**Comment by Pogogo007** [comment]
possible fix [https://github.com/CachyOS/CachyOS-Handheld/commit/57bbc7a8ed3475158e0da5224c6ca61331325c5b](https://github.com/CachyOS/CachyOS-Handheld/commit/57bbc7a8ed3475158e0da5224c6ca61331325c5b)
