### ISSUE TITLE
Wifi 6e on rog ally

### ISSUE THREAD

**Issue by joemossjr16** [CachyOS/CachyOS-Handheld#20]
Seems like wifi 6e isn't working on cachyos. It doesn't find it or anything. On bazzite it finds it but can't connect.  While in windows there is no issues.

**Comment by ptr1337** [comment]
As I told you on the discord - if it doesnt work on any distro, you should either try:
- An older kernel
- Report the issue to kernel issue tracker e.g: bugzilla.kernel.org

**Comment by ptr1337** [comment]
Appears to be solved, when setting the country code properly, check the arch wiki for that.
