### ISSUE TITLE
NEED HELP

### ISSUE THREAD

**Issue by Bladen123** [CachyOS/CachyOS-Handheld#21]
Hello there how can we disable the GRUB MENU ? I really didnt know where else i can ask this question.

**Comment by Pogogo007** [comment]
We use systemd-boot not grub. You can disable the menu by changing the timeout to 0 in /boot/loader/loader.conf

**Comment by Bladen123** [comment]
But if i use systemd-boot in terminal i get error , and in boot/loader/loader.conf i cant get access too

**Comment by Pogogo007** [comment]
/boot/loader/loader.conf is root only which means you need to modify it with Sudo. Sudo micro/nano or whatever utility you want. Also systemd-boot is not a command it's the name of the bootloader

**Comment by Bladen123** [comment]
understood thank you
