### ISSUE TITLE
More Strange ISSUES

### ISSUE THREAD

**Issue by Evilexium** [CachyOS/CachyOS-Handheld#25]
> Well after update i restarted and im granted with this ( look picture ) cant boot normal to steam os automaticaly
> 
> Also i have a question is there a possible way to install the new ISO without lose my Games on my NVMe ? ![IMG_20240714_215235](https://private-user-images.githubusercontent.com/175258307/348567498-c0d62439-069f-4874-801b-d74987042317.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTM4MjIsIm5iZiI6MTcyMDk5MzUyMiwicGF0aCI6Ii8xNzUyNTgzMDcvMzQ4NTY3NDk4LWMwZDYyNDM5LTA2OWYtNDg3NC04MDFiLWQ3NDk4NzA0MjMxNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQyMTQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWIyNDQ2ZGY1MTcwNzk1YWNlZTEwMTQ4NWEwN2FkMDE1YTU3YjcyYmQ4YTM2Yzc1NGU2YWQ2Y2Y5MDk0ZGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dMPSoAxvQGX66juo5puDgLz57fNEGpsLf2FAldMnn68)

Also when i do update it say warning that some packages lokal are newer than the others , also if i try install the gaming package it ask me if i want to delete cachyos-handheld and something about 

cachyos-gaming-meta-15-1 and cachyos-handheld 1.0.1-1 are in conflict
WARNING : fzf Local version 0.54.0-1) is never than cachyos-extra-zenver4 0.53.0-1.1
WARNING: pahole Local Version 1:1.27-3 is newer than cachyos-zenver4 1:1.27-2

If i do what the Terminal Say to delete cachyos-handheld as it makes conflict with the cachyos-gaming-meta-15-1 package than happens this what u see in the picture it grants me at next boot with login passwort and no steamOS

I dont want to be respectless i really enjoy this OS and all this hard work u guys do , but i feel like this os gets backwards a bit , it gets more and more issues and i dont understand why :(

**Comment by Evilexium** [comment]
> Well after update i restarted and im granted with this ( look picture ) cant boot normal to steam os automaticaly
> 
> Also i have a question is there a possible way to install the new ISO without lose my Games on my NVMe ? ![IMG_20240714_215235](https://private-user-images.githubusercontent.com/175258307/348567498-c0d62439-069f-4874-801b-d74987042317.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5OTM4MjIsIm5iZiI6MTcyMDk5MzUyMiwicGF0aCI6Ii8xNzUyNTgzMDcvMzQ4NTY3NDk4LWMwZDYyNDM5LTA2OWYtNDg3NC04MDFiLWQ3NDk4NzA0MjMxNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQyMTQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWIyNDQ2ZGY1MTcwNzk1YWNlZTEwMTQ4NWEwN2FkMDE1YTU3YjcyYmQ4YTM2Yzc1NGU2YWQ2Y2Y5MDk0ZGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dMPSoAxvQGX66juo5puDgLz57fNEGpsLf2FAldMnn68)

Also when i do update it say warning that some packages lokal are newer than the others , also if i try install the gaming package it ask me if i want to delete cachyos-handheld and something about gaming - meta

I dont want to be respectless i really enjoy this OS and all this hard work u guys do , but i feel like this os gets backwards a bit , it gets more and more issues and i dont understand why :(

**Comment by Pogogo007** [comment]
delete cachyos-gaming-meta. Cachyos-handheld provides all the same dependencies
