### ISSUE TITLE
[ISSUE] Suspending and wakeup

### ISSUE THREAD

**Issue by Evilexium** [CachyOS/CachyOS-Handheld#28]
Well everything worked fine on CachyOS Rog Ally, Since 1 or 2 days it makes strange issues since HHD Latest Updates. If i go sleep mode the LEDS act weird low dimmed red and wake up the ally no RGB no Controller support have to Hard reset the device everytime.

Indeed not very nice since 2 updates before everything worked as indeed , i feel like all this Fast Out off control Updates u guys make with HHD , just ruins this good software into Oblivion.

There are problems with RGBs , Spiral doesnt do anything beside stay Black , Sleep Mode break the controller support and HHD RGB LEDS , and controll of UI. The Configurations ask for token often even if the token is right it doesnt connect it say DOES HHD RUNN ?

Its annoying as F*** at this moment :)

EDIT : after that wake up where the side Buttons doesnt work and the LEDS , if i put the rog a second time in sleep and wake up suddenly works , so in short to explain . 1. the rog runs and controller and leds work , 2. i put sleep , no leds no side buttons after first wake up, 3. if i put again a second time to sleep and wake up a second time suddenly leds work and controller side buttons too. strange :( so i have to sleep , wake , sleep , wake to get it work .

Also i noticed now that when i put sleep and charge , after some seconds it wakes up hisself without me touching it ;( wtf is wrong ?

https://github.com/user-attachments/assets/697a435e-480d-42de-8a1b-d5f749f45724

**Comment by ptr1337** [comment]
Could you check with the 6.10.3 kernel?

**Comment by Evilexium** [comment]
I did it its a bit better but still same problems, sometimes works , and sometimes not.  if i put on suspend/sleep while in game  and than wake up its ramdom , either led are off but controller works in game  or vicewersa the controller doesnt get recognized in game but leds work and the overlay navigation can be controlled.  before this couple of latest updates this issue was there , allways worked.

**Comment by Evilexium** [comment]
Yeah Wellcome back DAMN ISSUE is here again since last Update either from CachyOS kernel or from HHD . Dont know but its 1 to 1 the same . everything worked perfectly almost a month now its back this MF ISSUE :(

**Comment by ptr1337** [comment]
There was only today following updates:
- Kernel was updated to 6.10.8
- hhd was updated (1hr ago)

**Comment by Evilexium** [comment]
What causes this ? yes i know thats when this started with 6.10.8-2

**Comment by ptr1337** [comment]
> What causes this ? yes i know thats when this started with 6.10.8-2

You can downgrade the kernel from the archive.
The difference between 6.10.7 and 6.10.8 you can find here:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.10.y

The best would be if you bisect the issue.

for downgrade:
`sudo pacman -U https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-deckify-6.10.7-2-x86_64_v3.pkg.tar.zst https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-deckify-headers-6.10.7-2-x86_64_v3.pkg.tar.zst`

**Comment by Evilexium** [comment]
ok will try that too. I also did with kernel manager remove the deckify 6.10.8-2 and installed the bore one 6.10.8-1 will try this too now , and than try downgrade . Thank you

**Comment by ptr1337** [comment]
You should not use another kernel then the deckify one. The others dont include any patches for the handheld devices

**Comment by Evilexium** [comment]
:( its first time i did it , ok i thought only difference is that it has no scheduler lavd the bore kernel . will reinstall deckify one back and downgrade. Thank you for the info

another question may i ask how can i deactivate the split lock , becasue if i do that how its mentioned in the cachyos guide it makes no difference God of War still runs with 25 fps-30 on windows over 60+ too . Alot of peoples say its becasue the new split lock in the linux kernel

**Comment by ptr1337** [comment]
> :( its first time i did it , ok i thought only difference is that it has no scheduler lavd the bore kernel . will reinstall deckify one back and downgrade. Thank you for the info
> 
> another question may i ask how can i deactivate the split lock , becasue if i do that how its mentioned in the cachyos guide it makes no difference God of War still runs with 25 fps-30 on windows over 60+ too . Alot of peoples say its becasue the new split lock in the linux kernel

Splitlock can be disabled how its mentioned in the wiki. You see in dmesg, in case of splitlock is still mitigating, e.g sudo dmesg |  grep splitlock

**Comment by Evilexium** [comment]
so there is no way to 100% disable that as i understand now ?

**Comment by Evilexium** [comment]
> > What causes this ? yes i know thats when this started with 6.10.8-2
> 
> You can downgrade the kernel from the archive. The difference between 6.10.7 and 6.10.8 you can find here: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/log/?h=linux-6.10.y
> 
> The best would be if you bisect the issue.
> 
> for downgrade: `sudo pacman -U https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-deckify-6.10.7-2-x86_64_v3.pkg.tar.zst https://archive.cachyos.org/archive/cachyos-v3/linux-cachyos-deckify-headers-6.10.7-2-x86_64_v3.pkg.tar.zst`

I did this and Now after reboot i get throw directly Into BIOS , If i select manualy to Boot from CachyOS loader it comes the blackscreen where normaly we can choose the Entry Kernel . Now there is nothing and i cant Boot anymore because somehow the loader Entrys Gone. Well 4 TB of Games and Savegames Gone 😮‍💨 i try since hours so recover or find a way how to Boot but since there is No Entry for CachyOS im lost .
