### ISSUE TITLE
[ISSUE] Steam and SteamOS UI

### ISSUE THREAD

**Issue by Evilexium** [CachyOS/CachyOS-Handheld#29]
Hello there , i dont know if this issue comes from CachyOS update, but it worked before and after i did update , if i go in gaming Mode SteamOS it stuck at Steam is Login is , and if i start steam in desktop more nothing happens :(

**Comment by ptr1337** [comment]
Steam is currently down

**Comment by Evilexium** [comment]
Oh sorry Sir , didnt know that what a coincidence that right after update was down and didnt work anymore , now it runs again u was right . i apologize for a ISSUE Call even if it wasnt.
