### ISSUE TITLE
Prompted beta updates on stable branch

### ISSUE THREAD

**Issue by SlowNicoFish** [CachyOS/CachyOS-Handheld#31]
When entering game mode steam prompts me about downloading a beta build even though I have chosen to be on the stable branch
![a108d2ef5c704a10ad66462d74ef7599ff7511dc.png](https://github.com/user-attachments/assets/0ca69511-3f88-415b-99ba-6cc7439a5b82)

**Comment by ptr1337** [comment]
Yes, just ignore it. Steam can not apply any updates over that.

**Comment by SlowNicoFish** [comment]
Sorry to reopen, but would it not be possible to add a 'os-branch-select' file like bazzite and chimera os but hardoce it to "stable" to not be prompted by steam os updates?
These other projects have the script under 'usr/lib/os-branch-select' (chimeraos) and usr/libexec/os-branch-select' (bazzite).
I guess gamemode reads this file to provide a branch selector
