### ISSUE TITLE
[ALLY] Controller Bug and RGB

### ISSUE THREAD

**Issue by Bladen123** [CachyOS/CachyOS-Handheld#32]
So after all this months and updates , its random sh!t happening since 3 weeks all runs like should and now i did the new kernel 6.11.0-deckify update and guess what that bug is back with sleep mode i mentioned 100 times on HHD and here at CachyOS . i dont know how its possible to gone and come and repeat this bug . i put sleep rog ally than wake up rgb is 1 sek glow up than goes black and the controller qam doesnt work have to reeboot system and after a sleep wake cycle same. this wasnt the case 1 kernel update before . this bug ruins every joy with this OS. for real this should be fixed once and for all . why still comes after couple of updates back this awkward bug ?

here i mentioned this in july 31

https://github.com/hhd-dev/hhd/issues/84

**Comment by ptr1337** [comment]
Hey, we will deprecate HHD for the Ally and Ally X and will be replaced by inputplumber.

Please run:
sudo pacman -R hhd adjuster hhd-ui
sudo pacman -S inputplumber-bin
sudo systemctl enable inputplumber.service

**Comment by Bladen123** [comment]
sir inputplumber does same almost worser , suspend power button doesnt work in gamemode  , also lose rgb randomly and the ally armory crate buttons doesnt work after wakeup on desktop mode.

**Comment by ptr1337** [comment]
> sir inputplumber does same almost worser , suspend power button doesnt work in gamemode , also lose rgb randomly and the ally armory crate buttons doesnt work after wakeup on desktop mode.

Then you need to compile you a custom kernel without these Ally Patches included. The MCU will be likely fixed soon related to sleep with upcoming updates.
I won't go the "userspace only" way, which hhd requests to do.

**Comment by Bladen123** [comment]
but sir i dont even know how to do that kernel without patches :) well looks like we have to wait for Valve for the Official Release maybe u can fork from them something for the ally later or maybe i talk nonsense hahaha not sure

**Comment by ptr1337** [comment]
> but sir i dont even know how to do that kernel without patches :) well looks like we have to wait for Valve for the Official Release maybe u can fork from them something for the ally later or maybe i talk nonsense hahaha not sure

No need to get rude :)
Anyways, then use SteamOS or any other distribution

**Comment by Bladen123** [comment]
noooo sir wasnt mean bad or rude , just as an idea good meant. i cant leave cachyos to good. beside this ally problems here and there sometimes.
