### ISSUE TITLE
Returning to desktop mode "desktop pc"

### ISSUE THREAD

**Issue by massatt212** [CachyOS/CachyOS-Handheld#5]
https://drive.google.com/file/d/1lSijvpkQxgByYRwe7T0GzHfTqpLaldIx/view?usp=drivesdk

Hopefully it's a simple fix

**Comment by ptr1337** [comment]
> https://drive.google.com/file/d/1lSijvpkQxgByYRwe7T0GzHfTqpLaldIx/view?usp=drivesdk
> 
> Hopefully it's a simple fix

Thanks for the video. Could you provide a sudo cachyos-bugreport.sh after that happened?

Thanks!

@Pogogo007

**Comment by massatt212** [comment]
I just uploaded it, to paste.caxhyos.org

**Comment by ptr1337** [comment]
> I just uploaded it, to paste.caxhyos.org

We need the link please.

**Comment by massatt212** [comment]
> > I just uploaded it, to paste.caxhyos.org
> 
> We need the link please. 

I just edited the post, sry about that

**Comment by Pogogo007** [comment]
Could you try uncommenting the DisplayServer=wayland line in /etc/sddm.conf.d/steam-deckify.conf. Make sure to reboot after

**Comment by massatt212** [comment]
> Could you try uncommenting the DisplayServer=wayland line in /etc/sddm.conf.d/steam-deckify.conf. Make sure to reboot after

Ok I'll try that in 5mins

**Comment by Pogogo007** [comment]
Could you try adding fbcon=vc:2-6 to your boot parameters

**Comment by massatt212** [comment]
> Could you try uncommenting the DisplayServer=wayland line in /etc/sddm.conf.d/steam-deckify.conf. Make sure to reboot after

It works good on my Intel PC but my amd PC with Intel arc is a problem.

**Comment by massatt212** [comment]
> Could you try adding fbcon=vc:2-6 to your kernel boot parameters
> 

I think it's a resolution problem, I swap to another PC and I'm getting into desktop mode, let me change my cable and see if that's the problem.

**Comment by massatt212** [comment]
> Could you try adding fbcon=vc:2-6 to your kernel boot parameters
> 

The problem is the display port, I swap.to HDMI and it works normal.

**Comment by massatt212** [comment]
> Could you try adding fbcon=vc:2-6 to your kernel boot parameters
> 

Problem is back with the HDMI, give me 20mins and I'll try that command.

**Comment by massatt212** [comment]
> Could you try adding fbcon=vc:2-6 to your kernel boot parameters
> 

I think this worked, I'll keep testing tomsee if it breaks down again.

**Comment by Pogogo007** [comment]
Nice. Do tell me after some usage how it goes
